name: Deploy Django DRF API

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 'Python 3.11.9'  

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar migraciones
        run: |
          python manage.py migrate

      - name: Crear superusuario automáticamente (opcional)
        env:
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_EMAIL: admin@example.com
          DJANGO_SUPERUSER_PASSWORD: adminpass
        run: |
          python manage.py createsuperuser --noinput || true

      - name: Correr servidor Django
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
